prometheus:
  url: http://ppp.default.svc
  port: 80

rules:
  default: false
  custom:
    - seriesQuery: 'http_requests_total{namespace!="",service!=""}'
      resources:
        overrides:
          namespace: { resource: "namespace" }
          service: { resource: "service" }
      name:
        matches: '^(.*)_total$'
        as: 'http_requests_per_second'
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)'
