apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaletestapp
  name: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
      annotations:
        # Аннотации для автоматического обнаружения Prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: scaletestapp
          image: ghcr.io/yandex-practicum/scaletestapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-metrics
          resources:
            limits:
              memory: "10Mi"
            requests:
              memory: "5Mi"