apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-svc-monitor
  namespace: monitoring  # Важно: ServiceMonitor должен быть в том же namespace, что и Prometheus Operator
  labels:
    release: prometheus-stack  # Должен совпадать с release name Helm установки
spec:
  selector:
    matchLabels:
      app: scaletestapp
  namespaceSelector:
    any: true  # Искать во всех namespace
  endpoints:
    - port: http-metrics
      interval: 10s
      path: /metrics