prometheus:
  url: http://prometheus-operator-kube-p-prometheus.monitoring.svc
  port: 9090

rules:
  default: true
  custom:
    - seriesQuery: '{__name__=~"http_requests_total"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'